/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateCardDialog: typeof import('./src/components/CreateCardDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrelloBoard: typeof import('./src/components/TrelloBoard.vue')['default']
    TrelloCard: typeof import('./src/components/TrelloCard.vue')['default']
    TrelloList: typeof import('./src/components/TrelloList.vue')['default']
  }
}
